#!/bin/sh

# ----------------------------------------
# Basic applications 
#-----------------------------------------

alt + {b,n,e,d}
	{firefox, chromium, thunar, discord}

# Terminal
super + Return
	alacritty

# Shortcut Helper
super + alt + h
	~/scripts/sxhkd-help-menu &

# Rofi menu
super + r
	rofi -show drun

# Power menu
super + Escape
	~/scripts/powermenu.sh &

# ----------------------------------------
# BSPWM hotkeys
#-----------------------------------------

# Kill application
super + {_, shift + }q
	bspc node -{c,k}

# Reset WM
super + alt + r
	bspc wm -r

# Reload sxhkdrc
super + shift + r
    pkill -usr1 -x sxhkd; notify-send 'sxhkd' 'Reloaded config'

# Floating mode
super + f
	bspc node focused -t floating

# Tilting mode
super + t
	bspc node focused -t tiled

# Change workspace
super + {1-5}
	bspc desktop -f {1-5}

# Move current window to a pre-selected space
super + shift + m
    bspc node -n last.!automatic

# Rotate tree
super + shift + {d,a}
    bspc node @/ -C {forward,backward}

# Send to desktop
super + shift + {1-5}
    bspc node -d '^{1-5}' --follow

# Swap the current node with the biggest window
super + g
	bspc node -s biggest.window

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
    bspc node -{f,s} {west,south,north,east}

# expand a window by moving one of its side outward
super + shift + {Left,Down,Up,Right}
    bspc node -z {left -40 0,bottom 0 40,top 0 -40,right 40 0}

# contract a window by moving one of its side inward
super + alt + {Left,Down,Up,Right}
    bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
    bspc node -v {-40 0,0 40,0 -40,40 0}
