#!/bin/bash

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd & 
sh ~/.config/polybar/launch.sh &
picom &
nitrogen --restore &
redshift &

# Workspaces
bspc monitor -d 1 2 3 4 5

# Window config
bspc config border_width            2
bspc config window_gap              10
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config paddingless_monocle     true
bspc config click_to_focus          true

bspc config focus_follows_pointer	true
bspc config pointer_modifier		mod1
