[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#83A598"
cyan = "#689d6a"
green = "#B8BB26"
magenta = "#D3869B"
red = "#FB4934"
white = "#a89984"
yellow = "#FABD2F"

[colors.primary]
background = "#151619"
foreground = "#ebdbb2"

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono NFM"

[window]
dynamic_title = false
opacity = 1

[window.padding]
x = 3
y = 5
